version: '2'
services:
    ocspv4-app:
        image: ocspv4
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ocspv4-mysql:3306/ocspv4?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ocspv4-mysql:
        extends:
            file: mysql.yml
            service: ocspv4-mysql
